apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
  namespace: mlops
data:
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "mlops_db"
  MLFLOW_TRACKING_URI: "http://mlflow-service:5000"
  MLFLOW_MODEL_NAME: "diabetes_model"
  MLFLOW_MODEL_ALIAS: "champion"
  MLFLOW_S3_ENDPOINT_URL: "http://minio-service:9000"
