apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deployment
  namespace: mlops
  labels:
    app: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: max181818/mlops-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8501
          envFrom:
            - configMapRef:
                name: streamlit-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 40
            periodSeconds: 15
            failureThreshold: 3
