# =========================================================
# k8s/airflow/airflow-pvc.yaml
# PersistentVolumeClaim para Airflow
# Almacena: DAGs, logs y el dataset diabetic_data.csv
# =========================================================

# PVC para los DAGs
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-pvc
  namespace: mlops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# PVC para los logs de Airflow
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-pvc
  namespace: mlops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
# PVC para el dataset (diabetic_data.csv)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-data-pvc
  namespace: mlops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
